version = "2.0"

[sink_group]
name = "/sink/full_type"
oml = ["full_type"]
[[sink_group.sinks]]
connect = "file_json_sink"
params = {  file = "full_type.json" }

[sink_group.sinks.expect]
ratio = 0.091
tol   = 0.01