version = "2.0"

[sink_group]
name = "/sink/skyeye_stat"
oml = ["skyeye_stat"]
[[sink_group.sinks]]
connect = "file_json_sink"
params = {  file = "skyeye_adm.json" }
[sink_group.sinks.expect]
ratio = 0.181
tol   = 0.01


[[sink_group.sinks]]
connect = "file_json_sink"
params = {  file = "skyeye_pdm.json" }

[sink_group.sinks.expect]
ratio = 0.181
tol   = 0.01
