version = "2.0"

[sink_group]
name = "pipe_sink"
rule = ["/pipe_demo/*"]
[[sink_group.sinks]]
name = "demo"
connect = "file_proto_sink"
params = {  file = "pipe.dat" }
[sink_group.sinks.expect]
ratio = 1.0
tol   = 0.02
