# 主要文件数据源（启用）
[[sources]]
key = "file_1"
connect = "file_src"
enable = true
tags = ["type:file", "purpose:benchmark"]
params = {  file = "gen.dat",instances = 1 }
#params = {  file = "gen.dat",instances = 1 }


[[sources]]
#enable = true
enable = false
key = "file_2"
connect = "file_src"
tags = ["type:file", "purpose:benchmark"]
params = {  file = "gen1.dat"  }
