version = "2.0"

[sink_group]
name = "default"

[[sink_group.sinks]]
name = "default_output"
connect = "blackhole_sink"
#params = { base = "./out", file = "default.dat" }
tags = ["sink:default", "format:proto-text"]

[sink_group.sinks.expect]
ratio = 0.01
tol = 0.02
