version = "2.0"

[sink_group]
name = "residue"
tags = ["group:residue", "type:infra"]

[[sink_group.sinks]]
name = "residue_output"
connect = "file_raw_sink"
params = { base = "./out", file = "residue.dat" }
tags = ["sink:residue", "format:raw"]
