version = "2.0"

[sink_group]
name = "default"
#match = { oml = [], rule = [] }

[[sink_group.sinks]]
connect = "file_proto_sink"
params = { base = "./out", file = "default.dat" }
[sink_group.sinks.expect]
ratio = 1.0
tol   = 0.02
