version = "2.0"

[sink_group]
name = "error"
oml = []
[[sink_group.sinks]]
connect = "file_raw_sink"
params = { base = "./out", file = "error.dat" }

[sink_group.sinks.expect]
ratio = 0.01
tol   = 0.02
