version = "2.0"

[sink_group]
name = "all"
rule = ["/*"]
parallel = 8
[[sink_group.sinks]]
name = "victorialogs_output"
connect = "victorialogs_sink"
params = { endpoint = "http://127.0.0.1:9428", insert_path = "/insert/jsonline", flush_interval_secs = 3}

[[sink_group.sinks]]
name = "main"
connect = "file_proto_sink"
#connect = "fast_file_sink"
params = { file = "all.dat" }
