version = "2.0"

[sink_group]
name = "/sink/benchmark2"
oml = ["example2"]
[[sink_group.sinks]]
connect = "file_kv_sink"
params = {  file = "benchmark_kv2.dat" }

[sink_group.sinks.expect]
ratio = 0.50
tol   = 0.02
