version = "1.0"
robust = "normal"

[models]
wpl = "./models/wpl"
oml = "./models/oml"
[topology]
sources = "./topology/sources"
sinks = "./topology/sinks"

[performance]
rate_limit_rps = 10000
parse_workers = 2

[rescue]
path = "./data/rescue"

[log_conf]
#level = "warn,ctrl=trace,dfx=info,data=debug"
level = "warn,ctrl=debug,dfx=info,data=warn"
output = "File"

[log_conf.file]
path = "./data/logs"

[stat]

[[stat.pick]]
key = "pick_stat"
target = "*"
fields = ["wpl_tag","wp_src_key"]

[[stat.parse]]
key = "parse_stat"
target = "*"
fields = ["wpl_tag", "wp_src_key"]

[[stat.sink]]
key = "sink_stat"
target = "*"
fields = ["wpl_tag","wp_src_key", "sink_category"]