services:
  # Kafka 集群
  kafka-1:
    container_name: kafka-1
    image: apache/kafka:4.1.1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:19092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:19092,EXTERNAL://127.0.0.1:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_RETENTION_MS: 600000   # 保存10m
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    #volumes:
    #  - ./tmp/kafka:/bitnami/kafka/data

  kafka-2:
    container_name: kafka-2
    image: apache/kafka:4.1.1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9093:9092"  # 宿主机9093映射到容器对外端口
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:19092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-2:19092,EXTERNAL://127.0.0.1:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_RETENTION_MS: 600000   # 保存10m
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3

  # Doris-1 集群
  doris-1-fe:
    image: apache/doris:fe-2.1.9
    hostname: doris-1-fe
    ports:
      - "8030:8030"  # 宿主机8030映射到容器8030
      - "9030:9030"
      - "9010:9010"
    environment:
      - FE_SERVERS=fe1:172.30.80.2:9010
      - FE_ID=1
    networks:
      custom_network_1:
        ipv4_address: 172.30.80.2

  doris-1-be:
    image: apache/doris:be-2.1.9
    hostname: doris-1-be
    ports:
      - "8040:8040"
      - "9050:9050"
    environment:
      - FE_SERVERS=fe1:172.30.80.2:9010
      - BE_ADDR=172.30.80.3:9050
    depends_on:
      - doris-1-fe
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://127.0.0.1:8040/api/health"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 20s
    networks:
      custom_network_1:
        ipv4_address: 172.30.80.3

  doris-1-init:
    image: curlimages/curl:8.10.1
    container_name: doris-1-init
    restart: "no"
    depends_on:
      doris-1-be:
        condition: service_started
    command:
      - /init/init_doris.sh
      - doris-1-fe
      - doris-1-be
      - /init/doris.sql
    volumes:
      - ./sql/doris.sql:/init/doris.sql:ro
      - ./sql/init_doris.sh:/init/init_doris.sh:ro
    networks:
      custom_network_1:
        ipv4_address: 172.30.80.4

  # Doris-2 集群
  doris-2-fe:
    image: apache/doris:fe-2.1.9
    hostname: doris-2-fe
    ports:
      - "8031:8030"  # 宿主机8031映射到容器8030
      - "9031:9030"
      - "9011:9010"
    environment:
      - FE_SERVERS=fe1:172.30.81.2:9010
      - FE_ID=1
    networks:
      custom_network_2:
        ipv4_address: 172.30.81.2

  doris-2-be:
    image: apache/doris:be-2.1.9
    hostname: doris-2-be
    ports:
      - "8041:8040"
      - "9051:9050"
    environment:
      - FE_SERVERS=fe1:172.30.81.2:9010
      - BE_ADDR=172.30.81.3:9050
    depends_on:
      - doris-2-fe
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://127.0.0.1:8040/api/health"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 20s
    networks:
      custom_network_2:
        ipv4_address: 172.30.81.3

  doris-2-init:
    image: curlimages/curl:8.10.1
    container_name: doris-2-init
    depends_on:
      doris-2-be:
        condition: service_started
    restart: "no"
    command:
      - /init/init_doris.sh
      - doris-2-fe
      - doris-2-be
      - /init/doris.sql
    volumes:
      - ./sql/doris.sql:/init/doris.sql:ro
      - ./sql/init_doris.sh:/init/init_doris.sh:ro
    networks:
      - custom_network_2

  victoria-logs-1:
    container_name: victoria-logs-1
    image: victoriametrics/victoria-logs:v1.43.0
    ports:
      - "9428:9428"
    # 数据存储目录,按需开启
    volumes:
      - vlogs-1:/storage
    command:
      - --envflag.enable
      - --envflag.prefix=VM_
      - --http.shutdownDelay=15s
      - --httpListenAddr=:9428
      - --loggerFormat=json
      - --retentionPeriod=1d
      - --storageDataPath=/storage
    environment:
      - TZ=Asia/Shanghai
    # 可选：添加健康检查（模拟 livenessProbe）
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://127.0.0.1:9428/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
  victoria-logs-2:
    container_name: victoria-logs-2
    image: victoriametrics/victoria-logs:v1.43.0
    ports:
      - "9429:9428"
    # 数据存储目录,按需开启
    volumes:
      - vlogs-2:/storage
    command:
      - --envflag.enable
      - --envflag.prefix=VM_
      - --http.shutdownDelay=15s
      - --httpListenAddr=:9428
      - --loggerFormat=json
      - --retentionPeriod=1d
      - --storageDataPath=/storage
    environment:
      - TZ=Asia/Shanghai
    # 可选：添加健康检查（模拟 livenessProbe）
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://127.0.0.1:9428/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  mysql-1:
    image: mysql:8.0
    container_name: mysql-1
    environment:
      MYSQL_ROOT_PASSWORD: "123456"   # Root 用户密码（必须设置）
      MYSQL_DATABASE: "default"          # 初始创建的数据库
      MYSQL_INNODB_BUFFER_POOL_SIZE: "1G"
      ALLOW_EMPTY_PASSWORD: "no"
    ports:
      - "3306:3306"
    volumes:
      - ./sql/mysql.sql:/docker-entrypoint-initdb.d/init.sql
  mysql-2:
    image: mysql:8.0
    container_name: mysql-2
    environment:
      MYSQL_ROOT_PASSWORD: "123456"   # Root 用户密码（必须设置）
      MYSQL_DATABASE: "default"          # 初始创建的数据库
      MYSQL_INNODB_BUFFER_POOL_SIZE: "1G"
      ALLOW_EMPTY_PASSWORD: "no"
    ports:
      - "3307:3306"
    volumes:
      - ./sql/mysql.sql:/docker-entrypoint-initdb.d/init.sql


  wp-monitor:
    container_name: wp-monitor
    image: dysec-docker-alpha.corp.dy-sec.com/wp-monitor:v2.0.1-alpha
    ports:
      - "25816:25816"
    healthcheck:
      test: ["CMD-SHELL", "ps -aux | grep /app/wp_monitor -q"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    volumes:
      # 挂载配置文件目录
      - ./wp-monitor:/app/config

  victoria-metrics:
    container_name: victoria-metrics
    image: victoriametrics/victoria-metrics:v1.133.0
    ports:
      - "8428:8428"
    volumes:
      # 数据存储目录，按需开启
      - metrics_data:/storage
      - ./victoria-metrics/scrape.yml:/scrapeconfig/scrape.yml:ro  # 挂载 scrape 配置
    command:
      - --envflag.enable
      - --envflag.prefix=VM_
      - --httpListenAddr=:8428
      - --loggerFormat=json
      - --promscrape.config=/scrapeconfig/scrape.yml
      - --retentionPeriod=15d
      - --storageDataPath=/storage
    environment:
      - TZ=Asia/Shanghai
    # 可选：添加健康检查（模拟 livenessProbe）
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://127.0.0.1:8428/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  custom_network_1:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.80.0/24

  custom_network_2:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.81.0/24

volumes:
  vlogs-1:
    driver: local
  vlogs-2:
    driver: local
  metrics_data:
    driver: local
