version = "1.0"
robust = "normal"

[models]
wpl = "./models/wpl"
oml = "./models/oml"
sources = "./models/sources"
sinks = "./models/sinks"

[performance]
rate_limit_rps = 10000
parse_workers = 2

[rescue]
path = "./data/rescue"

[log_conf]
#level = "warn,ctrl=trace,dfx=info,data=debug"
level = "warn,ctrl=debug,dfx=info,data=warn"
output = "File"

[log_conf.file]
path = "./data/logs"

[stat]
#window_sec = 60

[[stat.pick]]
key = "pick_stat"
target = "*"
#fields = ["access_source"]
#top_n = 20

[[stat.parse]]
key = "parse_stat"
target = "*"
#fields = ["access_ip", "log_desc", "log_type"]
fields = [ "log_desc", "log_type"]
#top_n = 20

[[stat.sink]]
key = "sink_stat"
target = "*"
#fields = ["access_ip", "log_desc", "log_type"]
fields = [ "log_desc", "log_type"]
#top_n = 20
