version = "2.0"

[sink_group]
name = "/sink/skyeye_stat"
oml = ["skyeye_stat"]
[[sink_group.sinks]]
connect = "file_json_sink"
params = {  file = "skyeye_stat_json.dat" }

[[sink_group.sinks]]
connect = "file_kv_sink"
params = { file = "skyeye_stat_kv.dat" }
