apiVersion: 1
datasources:
  - name: VictoriaMetrics
    type: victoriametrics-metrics-datasource
    uid: victoriametrics-metrics-datasource
    access: proxy
    url: http://victoria-metrics:8428
    isDefault: true
    editable: true
  - name: VictoriaLogs
    type: victoriametrics-logs-datasource
    uid: victoriametrics-logs-datasource
    access: proxy
    url: http://victoria-logs:9428
    editable: true
