version = "2.0"

[sink_group]
name = "/sink/benchmark"
oml = ["/oml/benchmark"]
[[sink_group.sinks]]
connect = "file_proto_sink"
params = {  file = "benchmark.dat" }


[sink_group.sinks.expect]
ratio = 0.66
tol   = 0.02
