version = "2.0"

[sink_group]
name = "monitor"
oml = []
[[sink_group.sinks]]
connect = "file_json_sink"
params = {  file = "monitor.dat" }

[sink_group.sinks.expect]
max = 1.0


# [[sink_group.sinks]]
# connect = "kafka_sink"
# name = "kafka_generator_output"
# params= { topic = "monitor" ,brokers = "localhost:9092" }