version = "2.0"

[sink_group]
name = "monitor"
[[sink_group.sinks]]
name = "monitor"
connect = "file_proto_sink"
params = {  file = "monitor.dat" }
[sink_group.sinks.expect]
min   = 0.001

#[[sink_group.sinks]]
#name = "prometheus"
#connect = "prometheus_sink"
