[[sources]]
enable =  true
key = "tcp_1"
connect = "tcp_src"
#params = { prefer_newline = true , port =19001, instances = 1}
params = { prefer_newline = true , port =19001, instances = 1}


[[sources]]
enable = false
key = "tcp_2"
connect = "tcp_src"
params = {  prefer_newline = true , port = 19002}
