[[connectors]]
id = "mysql_sink"
type = "mysql"
allow_override = ["endpoint", "username", "password","database","table","columns"]
[connectors.params]
endpoint = "localhost:3306"
username = "${SEC_MYSQL_USER}"
password = "${SEC_MYSQL_PWD}"
database = "wparse"
table = "nginx_logs"
columns = ["sip", "timestamp", "http/request", "status", "size", "referer", "http/agent"]
batch = 20
