version = "1.0"

[generator]
mode = "sample"
count = 100000
speed = 10000
parallel = 4

[output]
# 仅当存在 connect 时，其他 output 字段和旧式 [output.*] 子块将被忽略
name = "gen_out"
connect = "tcp_sink"
params = { port= 19002 }


[logging]
level = "debug,mtrc=error,ctrl=debug,data=trace"
output = ""
file_path = "./data/logs"