version = "2.0"

[sink_group]
name = "testcase"
oml = ["/oml/example"]
[[sink_group.sinks]]
name = "file_proto_sink"
connect = "file_proto_sink"
[sink_group.sinks.params]
file = "events.parsed.prototext"
[sink_group.sinks.expect]
ratio = 0.50
tol   = 0.01

[[sink_group.sinks]]
name = "kafka_out"
connect = "kafka_sink"
[sink_group.sinks.params]
topic= "wp.testcase.events.parsed"
