version = 2
# base_dir 默认 "."（相对本文件目录），可省略
base_dir = "."

[default]
transaction = true
batch_size  = 2000
on_error    = "fail"

[csv]
has_header = true
delimiter  = ","
encoding   = "utf-8"
trim       = true

[[tables]]
enabled = true
name = "example_score"
columns.by_header = ["name", "math", "chinese", "english"]
[tables.expected_rows]
min = 5
max = 110

[[tables]]
enabled = true
name = "address"
columns.by_index = [0]
[tables.csv]
has_header = false
[tables.expected_rows]
min = 5
max = 110
