version = "2.0"
[sink_group]
name = "benchmark"
parallel = 3
oml = ["benchmark"]
[[sink_group.sinks]]
name = "blackhole"
connect = "blackhole_sink"
#use = "file_default"
#params = { base = "./out", file = "3:benchmark.dat" }
#[sink_group.sinks.expect]
#ratio = 0.66
#tol   = 0.011
