version = "2.0"
[sink_group]
name = "example/simple"
parallel = 3
oml = ["/oml/example/simple"]
[[sink_group.sinks]]
name = "blackhole"
connect = "blackhole_sink"
#use = "file_default"
#params = { base = "./out", file = "simple.dat" }
#[sink_group.sinks.expect]
#ratio = 0.66
#tol   = 0.011
