version = "1.0"

[models]
wpl = "../../models/wpl"
oml = "../../models/oml"
[topology]
sources = "../sources"
sinks = "../../sinks/trans_to_file"

[performance]
parse_workers = 2
rate_limit_rps = 0

[rescue]
path = "./data/rescue"

[log_conf]
level = "warn,ctrl=info,launch=info,klib=info"
output = "File"
[log_conf.file]
path = "./data/logs"

[stat]
window_sec = 60

[[stat.pick]]
key = "pick_stat"
target = "*"

[[stat.parse]]
key = "parse_stat"
target = "*"

[[stat.sink]]
key = "sink_stat"
target = "*"
