version = "1.0"

[generator]
mode = "sample"
count = 1000
speed = 1000
parallel = 2

[output]
# 仅当存在 connect 时，其他 output 字段和旧式 [output.*] 子块将被忽略
name = "gen_out"
# 覆写允许的参数（参考 connectors/sink.d 中对应连接器 allow_override）
#connect = "file_raw_sink"
connect = "syslog_tcp_sink"
params = { port= 1515  }
#connect = "syslog_udp_sink"
#params = { addr = "127.0.0.1"  }
#params = { file= "gen.dat", base = "./data/in_dat"  }

[logging]
level = "warn"
module_levels = ["ctrl=info", "launch=info"]
output = "file"
file_path = "./data/logs/"
