version = "2.0"

[sink_group]
name = "/sink/benchmark"
oml = ["/oml/benchmark"]
[[sink_group.sinks]]
name = "proto"
connect = "file_proto_sink"
params = {  file = "benchmark.dat" }
[sink_group.sinks.expect]
ratio = 1.0
tol   = 0.01
