version = "1.0"
robust = "normal"

[models]
wpl = "./models/wpl"
oml = "./models/oml"
[topology]
sources = "./topology/sources"
sinks = "./topology/sinks"

[performance]
rate_limit_rps = 1000
parse_workers = 2

[rescue]
path = "./data/rescue"

[log_conf]
level = "warn,ctrl=info,data=debug"
output = "File"

[log_conf.file]
path = "./data/logs/"

[stat]
[[stat.pick]]
key = "pick_stat"
target = "*"
fields = ["wp_src_key"]

[[stat.parse]]
key = "parse_stat"
target = "*"
fields = ["wp_src_key"]

[[stat.sink]]
key = "sink_stat"
target = "*"
fields = ["wp_src_key"]
