version = "2.0"

[sink_group]
name = "error"
oml = []
tags = ["group:error", "type:infra"]

[[sink_group.sinks]]
name = "error_output"
connect = "file_raw_sink"
params = { base = "./out", file = "error.dat" }
tags = ["sink:error", "format:raw"]

[sink_group.sinks.expect]
ratio = 0.01
tol = 0.02
