version = "2.0"

[sink_group]
name = "miss"
oml = []
tags = ["group:miss", "type:infra"]

[[sink_group.sinks]]
name = "miss_output"
connect = "file_raw_sink"
params = { base = "./out", file = "miss.dat" }
tags = ["sink:miss", "format:raw"]

[sink_group.sinks.expect]
max = 2.0
