version = "2.0"

[sink_group]
name = "monitor"
tags = ["group:monitor", "type:infra"]

[[sink_group.sinks]]
name = "monitor_output"
connect = "file_proto_sink"
params = { base = "./out", file = "monitor.dat" }
tags = ["sink:monitor", "format:proto-text"]
