version = "2.0"

[sink_group]
name = "default"
oml = []
tags = []

[[sink_group.sinks]]
connect = "file_proto_sink"
tags = []

[sink_group.sinks.params]
file = "default.dat"

[sink_group.sinks.expect]
ratio = 0.0
tol = 0.02
