version = "1.0"

[generator]
mode = "sample"
count = 100000000
speed =  10000
parallel =  4

[output]
# 仅当存在 connect 时，其他 output 字段和旧式 [output.*] 子块将被忽略
name = "gen_out"
# 覆写允许的参数（参考 connectors/sink.d 中对应连接器 allow_override）
#connect = "file_raw_sink"
connect = "blackhole_sink"
#params = { port= 19001  }
#connect = "syslog_udp_sink"
#params = { addr = "127.0.0.1"  }
#params = { file= "gen.dat", base = "./data/in_dat"  }

[logging]
level = "warn"
output = "file"
file_path = "./data/logs/"
