version = "2.0"

[sink_group]
name = "/example/"
oml = ["/oml/example/simple"]
[[sink_group.sinks]]
name = "proto"
connect = "file_proto_sink"
[sink_group.sinks.params]
file = "simple.dat"
[sink_group.sinks.expect]
ratio = 0.33
tol   = 0.02

[[sink_group.sinks]]
name = "kv"
connect = "file_kv_sink"
[sink_group.sinks.params]
file = "simple.kv"
[sink_group.sinks.expect]
ratio = 0.33
tol   = 0.02

[[sink_group.sinks]]
name = "json"
connect = "file_json_sink"
[sink_group.sinks.params]
file = "simple.json"
[sink_group.sinks.expect]
ratio = 0.33
tol   = 0.02
