version = "2.0"

[sink_group]
name = "/sink/benchmark"
oml = ["sys"]
[[sink_group.sinks]]
connect = "file_rescue_sink"
params = {  file = "benchmark.dat" }
[sink_group.sinks.expect]
ratio = 0.66
tol   = 0.02
