[[sources]]
enable = true
key = "tcp_1"
connect = "tcp_src"
tags = ["type:tcp", "purpose:benchmark"]
params = { prefer_newline = true, port = 19001 }

[[sources]]
enable = false
key = "tcp_2"
connect = "tcp_src"
tags = ["type:tcp", "purpose:benchmark"]
params = { prefer_newline = true, port = 19002 }
