version = "2.0"

[sink_group]
name = "/sink/example"
oml = ["example"]
[[sink_group.sinks]]
connect = "file_kv_sink"
params = {  file = "example.dat" }
[sink_group.sinks.expect]
ratio = 0.33
tol   = 0.01

[[sink_group.sinks]]
connect = "file_kv_sink"
params = {  file = "example.bak" }
[sink_group.sinks.expect]
ratio = 0.33
tol   = 0.01
