version = 2
base_dir = "."

[default]
transaction = true
batch_size  = 2000
on_error    = "fail"

[csv]
has_header = true
delimiter  = ","
encoding   = "utf-8"
trim       = true

[[tables]]
enabled = true
name = "example"
dir  = "example"
columns.by_header = ["name", "pinying"]
[tables.expected_rows]
min = 1
max = 100

[[tables]]
enabled = true
name = "address"
dir  = "address"
columns.by_header = ["value"]
[tables.expected_rows]
min = 1
max = 100
