[[connectors]]
id = "syslog_udp_src"
type = "syslog"
allow_override = ["addr", "port", "protocol", "udp_recv_buffer", "header_mode", ]
[connectors.params]
addr = "0.0.0.0"
port = 1514
protocol = "udp"
header_mode = "skip"
udp_recv_buffer = 8388608
